"""add is_mock_embedding to document_chunks

Revision ID: 247da76daefe
Revises: a225e36f0190
Create Date: 2026-07-14 05:11:02.513107

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247da76daefe'
down_revision: Union[str, None] = 'a225e36f0190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('is_mock_embedding', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'is_mock_embedding')
    # ### end Alembic commands ###
