"""add_peer_tickers_to_company

Revision ID: 62063797a222
Revises: b3f1d2e9c740
Create Date: 2026-07-27 12:18:56.225196

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62063797a222'
down_revision: Union[str, None] = 'b3f1d2e9c740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('peer_tickers', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'peer_tickers')
    # ### end Alembic commands ###
