"""add_market_intelligence_tables

Revision ID: 74fd3e5965e1
Revises: c0bb69a3682d
Create Date: 2026-07-03 14:55:21.982178

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74fd3e5965e1'
down_revision: Union[str, None] = 'c0bb69a3682d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_events',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Enum('macroeconomic', 'regulatory', 'geopolitical', 'industry', 'company_specific', 'general', name='newscategory'), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'negative', 'neutral', name='newssentiment'), nullable=False),
    sa.Column('impact_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='marketimpactlevel'), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_events_event_type'), 'market_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_market_events_id'), 'market_events', ['id'], unique=False)
    op.create_index(op.f('ix_market_events_impact_level'), 'market_events', ['impact_level'], unique=False)
    op.create_index(op.f('ix_market_events_sentiment'), 'market_events', ['sentiment'], unique=False)
    op.create_index(op.f('ix_market_events_title'), 'market_events', ['title'], unique=False)
    op.create_table('news_articles',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('macroeconomic', 'regulatory', 'geopolitical', 'industry', 'company_specific', 'general', name='newscategory'), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'negative', 'neutral', name='newssentiment'), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_category'), 'news_articles', ['category'], unique=False)
    op.create_index(op.f('ix_news_articles_content_hash'), 'news_articles', ['content_hash'], unique=True)
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_sentiment'), 'news_articles', ['sentiment'], unique=False)
    op.create_index(op.f('ix_news_articles_source'), 'news_articles', ['source'], unique=False)
    op.create_index(op.f('ix_news_articles_title'), 'news_articles', ['title'], unique=False)
    op.create_table('news_companies',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_companies_article_id'), 'news_companies', ['article_id'], unique=False)
    op.create_index(op.f('ix_news_companies_company_id'), 'news_companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_news_companies_id'), 'news_companies', ['id'], unique=False)
    op.create_table('news_industries',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('industry_name', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_industries_article_id'), 'news_industries', ['article_id'], unique=False)
    op.create_index(op.f('ix_news_industries_id'), 'news_industries', ['id'], unique=False)
    op.create_index(op.f('ix_news_industries_industry_name'), 'news_industries', ['industry_name'], unique=False)
    op.alter_column('event_industries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('event_industries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('financial_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('financial_evidence', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('financial_metric_provenance', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('financial_metric_provenance', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('financial_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('financial_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('financial_periods', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('financial_periods', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('financial_statements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('financial_statements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('industries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('industries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('industries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('industries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('financial_statements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('financial_statements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('financial_periods', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('financial_periods', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('financial_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('financial_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('financial_metric_provenance', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('financial_metric_provenance', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('financial_evidence', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('financial_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event_industries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event_industries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_news_industries_industry_name'), table_name='news_industries')
    op.drop_index(op.f('ix_news_industries_id'), table_name='news_industries')
    op.drop_index(op.f('ix_news_industries_article_id'), table_name='news_industries')
    op.drop_table('news_industries')
    op.drop_index(op.f('ix_news_companies_id'), table_name='news_companies')
    op.drop_index(op.f('ix_news_companies_company_id'), table_name='news_companies')
    op.drop_index(op.f('ix_news_companies_article_id'), table_name='news_companies')
    op.drop_table('news_companies')
    op.drop_index(op.f('ix_news_articles_title'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_source'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_sentiment'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_content_hash'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_category'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_market_events_title'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_sentiment'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_impact_level'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_id'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_event_type'), table_name='market_events')
    op.drop_table('market_events')
    # ### end Alembic commands ###
