from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class AIResponse(BaseModel):
    """
    Structured research report generated by OpenAI/Gemini based on orchestrator contexts.
    """
    executive_summary: str = Field(..., description="High-level summarization of findings")
    key_insights: List[str] = Field(..., description="Key insights and critical take-aways")
    supporting_evidence: List[str] = Field(..., description="Explicit, grounded supporting points matching context facts")
    risks_limitations: List[str] = Field(..., description="Identified risks, caveats, or gaps in the available information")
    sources: List[str] = Field(..., description="Cited source documents and relevant page indexes (e.g., 'Annual Report 2026, Page 4')")
    tabular_analysis: Optional[str] = Field(None, description="Markdown table comparing relevant metrics")
    
    confidence_score: Optional[float] = Field(None, description="Report confidence score (0.0 to 1.0)")
    assumptions_used: Optional[List[str]] = Field(None, description="Assumptions used in analysis or calculations")
    missing_inputs_explanation: Optional[str] = Field(None, description="Explanation of missing inputs if data is insufficient")
    cited_sources_detailed: Optional[List[Dict[str, Any]]] = Field(None, description="Structured detailed citations (doc_title, page, section, chunk_idx)")
    provider: Optional[str] = Field("gemini", description="LLM provider that generated the response (gemini, openai, ollama, mock, or error)")
    generation_mode: Optional[str] = Field(
        None,
        description="Generation mode: 'llm' (normal), 'ollama_fallback', or 'fallback_raw_chunks' (degraded)"
    )
    is_degraded: bool = Field(
        False,
        description="True when the response was generated by the raw-chunks fallback rather than an LLM"
    )
    error_message: Optional[str] = Field(None, description="Detailed error/failure message if LLM call failed")
    error_type: Optional[str] = Field(None, description="Structured error category: 'rate_limited', 'json_parse_failure', 'api_error', etc.")
    evidence_source_type: Optional[str] = Field(
        None,
        description=(
            "Describes the actual data source used for evidence in this response. "
            "Values: 'live_news' (RSS/APITube internet fetch), 'rag_documents' (PDF/DB vector chunks), "
            "'mixed' (both sources present), 'none' (no evidence chunks). "
            "Set by the backend; the frontend must use this field — never infer from chunk heuristics."
        )
    )
